# -*- coding: utf-8 -*-
"""Mid-Term Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VZTWJg4zFp9G-In9jNOoC-UwGlSOS3QP

# Midterm Project – Introduction to Data Science
## Sahar Ben Ezra – 319074837

## Dataset Chosen: "Fast Food Restaurants Across America"  
**Source:** https://www.kaggle.com/datasets/imtkaggleteam/fast-food-restaurants-across-america

### Why we chose this dataset:  
We chose this dataset because fast food is a major part of American consumer culture.  
It allows us to explore business distribution patterns, brand presence, and geographic trends across the United States.  
The dataset is clean, well-structured, and suitable for creating insightful visualizations and data-driven insights using Python tools like pandas and seaborn.
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("imtkaggleteam/fast-food-restaurants-across-america")

print("Path to dataset files:", path)

import os

# List files in the extracted dataset folder
dataset_folder = '/root/.cache/kagglehub/datasets/imtkaggleteam/fast-food-restaurants-across-america/versions/1'
print(os.listdir(dataset_folder))

import pandas as pd

# Define full path to the file
file_path = '/root/.cache/kagglehub/datasets/imtkaggleteam/fast-food-restaurants-across-america/versions/1/FastFoodRestaurants.csv'

# Load the dataset
df = pd.read_csv(file_path)

# Clean column names
df.columns = df.columns.str.strip()

# Show basic preview
df.head()

# Basic structure
print("Shape of dataset:", df.shape)
print("\nColumn types:")
print(df.dtypes)

# Count missing values
print("\nMissing values per column:")
print(df.isnull().sum())

# Unique brands
print("\nNumber of unique fast food brands:", df['name'].nunique())
print("Top 10 brands:")
print(df['name'].value_counts().head(10))

"""## Dataset Structure

The dataset contains information about fast food restaurants across the United States.  
It includes geographic coordinates, brand names, addresses, and state/province codes.  
This initial investigation provides the size of the dataset, data types of each column, missing values, and a breakdown of the top brands.

We can already observe that "name" (brand) is a key variable for analysis, and that "province" can help us analyze geographic distribution by state.

"""

import seaborn as sns
import matplotlib.pyplot as plt

# Top 10 brands
top_brands = df['name'].value_counts().head(10).reset_index()
top_brands.columns = ['Brand', 'Count']

# Plot
plt.figure(figsize=(10,6))
sns.barplot(data=top_brands, x='Count', y='Brand', palette='viridis')
plt.title('Top 10 Fast Food Brands in the U.S.')
plt.xlabel('Number of Locations')
plt.ylabel('Brand')
plt.grid(axis='x')
plt.tight_layout()
plt.show()

"""### Brand Distribution

This bar chart shows the 10 most common fast food brands across the U.S.  
We can clearly see that major national chains like McDonald's and Burger King dominate the landscape.  
This variable is useful for comparing brand presence across different geographic regions.

"""

# Top 15 states by number of restaurants
top_states = df['province'].value_counts().head(15).reset_index()
top_states.columns = ['State', 'Count']

# Plot
plt.figure(figsize=(10,6))
sns.barplot(data=top_states, x='Count', y='State', palette='crest')
plt.title('Top 15 U.S. States by Number of Fast Food Restaurants')
plt.xlabel('Number of Locations')
plt.ylabel('State')
plt.grid(axis='x')
plt.tight_layout()
plt.show()



"""### State-wise Distribution

This chart displays the 15 U.S. states with the highest number of fast food locations.(Within the 10,000 branches in the database...)
We observe that highly populated states like Texas and California have the largest number of restaurants.  
This variable is useful for understanding regional density and comparing brand presence across different states.

"""

# Filter only California (CA)
df_ca = df[df['province'] == 'CA']

# Count top 10 brands in California
top_brands_ca = df_ca['name'].value_counts().head(10).reset_index()
top_brands_ca.columns = ['Brand', 'Count']

# Plot
plt.figure(figsize=(10,6))
sns.barplot(data=top_brands_ca, x='Count', y='Brand', palette='mako')
plt.title('Top 10 Fast Food Brands in California (CA)')
plt.xlabel('Number of Locations')
plt.ylabel('Brand')
plt.grid(axis='x')
plt.tight_layout()
plt.show()

"""### Brand Distribution in California

This bar chart shows the 10 most common fast food brands in the state of California.  
It helps compare brand dominance on a regional level, and may reveal differences in brand popularity across different U.S. states.

"""

# Filter for Texas (TX)
df_tx = df[df['province'] == 'TX']

# Count top 10 brands in Texas
top_brands_tx = df_tx['name'].value_counts().head(10).reset_index()
top_brands_tx.columns = ['Brand', 'Count']

# Plot
plt.figure(figsize=(10,6))
sns.barplot(data=top_brands_tx, x='Count', y='Brand', palette='flare')
plt.title('Top 10 Fast Food Brands in Texas (TX)')
plt.xlabel('Number of Locations')
plt.ylabel('Brand')
plt.grid(axis='x')
plt.tight_layout()
plt.show()

"""### Regional Focus – Texas (TX)

This chart displays the most popular fast food brands in Texas.  
We can see whether national leaders such as McDonald’s dominate, or if Texas has its own regional preferences.  
Comparing this chart with other states highlights regional variation in fast food brand popularity.

## Insights

### Insight 1: Brand Dominance

**Observation:**  
The most common fast food brand in the U.S. is McDonald’s, followed by Burger King and Taco Bell.  
These top brands have significantly more locations than others.

**Implication:**  
These companies likely have the largest national reach and marketing footprint, which may affect regional competition.

**Supported by:**  
Bar chart of top 10 brands across the U.S.


### Insight 2: Geographic Concentration

**Observation:**  
California and Texas have the highest number of fast food restaurants among all U.S. states.  
Other states with high concentrations include Ohio and Florida.

**Implication:**  
Highly populated or car-dependent states have greater density of fast food chains, which may reflect both demand and infrastructure.

**Supported by:**  
State-level bar chart of number of locations.


### Insight 3: Regional Brand Preferences

**Observation:**  
In California, McDonald’s is still the leader, but regional chains may also appear in the top 10 depending on the state.  
Different states show different top brands.

**Implication:**  
Fast food preferences vary by region, which can influence local advertising strategies and brand partnerships.

**Supported by:**  
Brand distribution chart for California and Texas.
"""

pip install streamlit

import os

dataset_folder = '/root/.cache/kagglehub/datasets/imtkaggleteam/fast-food-restaurants-across-america/versions/1'
print(os.listdir(dataset_folder))

import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Title
st.title("🍔 Fast Food Brand Explorer (USA)")

# Load data
@st.cache_data
def load_data():
    path = '/root/.cache/kagglehub/datasets/imtkaggleteam/fast-food-restaurants-across-america/versions/1/FastFoodRestaurants.csv'
    df = pd.read_csv(path)
    df.columns = df.columns.str.strip()
    return df

df = load_data()

# Sidebar
state = st.sidebar.selectbox("Choose a U.S. state:", sorted(df['province'].dropna().unique()))

# Filter by selected state
filtered_df = df[df['province'] == state]

# Count top brands
top_brands = filtered_df['name'].value_counts().head(10).reset_index()
top_brands.columns = ['Brand', 'Count']

# Display chart
st.subheader(f"Top 10 Fast Food Brands in {state}")
fig, ax = plt.subplots(figsize=(10, 6))
sns.barplot(data=top_brands, x='Count', y='Brand', ax=ax, palette='Spectral')
ax.set_title(f"Top 10 Brands in {state}")
st.pyplot(fig)
st.caption("Data source: Kaggle – Fast Food Restaurants Across America")

